name: Generate PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - name: Generate HTML
        uses: docker://pandoc/core:2.11.2
        with:
          args: >-
            --standalone
            --from markdown+ascii_identifiers 
            --output=result.html
            --metadata title="Stanovy Svobodných"
            -t html5
            -A .pandoc/footer.html
            -H .pandoc/header.html
            index.md
      - run: sudo apt-get update 
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get install xvfb libfontconfig wget
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo apt install -f ./wkhtmltox_0.12.5-1.bionic_amd64.deb
      - name: Generate PDF
        run: xvfb-run wkhtmltopdf --page-size a4 --title "Stanovy Svobodných" --margin-bottom 35 --margin-top 15 --margin-right 0 --margin-left 0 --enable-local-file-access --header-spacing 12 --header-html .wkhtmltopdf/header.html --footer-spacing 12 --footer-html .wkhtmltopdf/footer.html --replace "schvaleno" "1.1.2020" result.html output/result.pdf
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
